version: '3'

services:
  # Servicio del backend
  orionstock-indumentaria-backend:
    build: ./orionstock-indumentaria-backend
    mem_limit: 512m
    ports:
      - "80:8080"
    environment:
      DB_URL: jdbc:mysql://orionstock_indumentaria:3306/orionstockindumentaria?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      orionstock_indumentaria:
        condition: service_healthy
    volumes:
      # Mapea la carpeta de recursos estáticos de tu proyecto al contenedor
      - ./orionstock-indumentaria-backend/src/main/resources/static:/app/static
    networks:
      - orionnet

  # Servicio de base de datos MySQL
  orionstock_indumentaria:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: orionstockindumentaria
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - orionnet

# Definir una red compartida entre los servicios
networks:
  orionnet:
    driver: bridge
